### ISSUE TITLE
Lacking of proper credits

### ISSUE THREAD

**Issue by gmxavier** [camaramm/tep2py#3]
Mauricio, it would be nice that in your README.md you give proper credits to the original modification in the FORTRAN file made by me 3 years ago and available as a R package [here](https://github.com/gmxavier/TEP-meets-LSTM). I read a paper recently that lacks the proper citation, maybe due to this fault. There is a disclaimer in the FORTRAN file indeed:

 Users should cite this version using the following reference:
G.M. Xavier and J.M. Seixas, "Fault Detection and Diagnosis in a
Chemical Process using Long Short-Term Memory Recurrent Neural Network".
In Proceedings 31st International Joint Conference on Neural Networks (IJCNN),
(Rio de Janeiro, Brazil), IEEE, IEEE, July 2018. 8 pages, to appear

**Comment by camaramm** [comment]
@gmxavier, I'm sorry for any inconvenient it may have caused. I wasn't aware of any citing problems related to the modified Fortran version you have published. Please note that citation, as well as complete license information was included in commit https://github.com/camaramm/tep2py/commit/8605cc251c3f60390e8066324e8c2b0ad4979ef1.

Your suggestion was included in commit https://github.com/camaramm/tep2py/commit/112cd3134cbc4632f4c772d97872c0c6f175f785. I hope it helps proper citation of your work.
